### ISSUE TITLE
Thanks for the feedback

### ISSUE THREAD

**Issue by guangyusong** [mrtyson93/e28#1]
Thank you for taking the time to review my P3 and provide feedback. Your comments were on point. I resorted to reusing a lot of logic and code from the lectures after aiming too high at first and was unable to produce a functional MVP by the deadline. I will keep your comments in mind and will definitely make a better final product for P4.

One thing I really struggled with is that I find it difficult to unsee code, especially when I fail to think of a better implementation. Do you have any tips for that?

**Comment by mrtyson93** [comment]
I've been in your position before and I think having the difficulty to unsee code results from a lack of understanding the course material. It's easier to come up with ideas when you understand the material fully and can envision different ways you can apply it.

I was able to spend a couple days just thinking about what I wanted to do applying the topics we learned in a different way and it wasnt too crazy to come up with that.

Maybe a quick review of the topics and going over code or googling about them would help.
